export const recentPapers = [
  { year: "2026", venue: "AAAI", title: "Probabilistic Hash Embeddings for Online Learning of Categorical Features", authors: "Aodong Li, Abishek Sankararaman, Balakrishnan Murali Narayanaswamy", href: "https://arxiv.org/abs/2511.20893" },
  { year: "2025", venue: "EMNLP", title: "FairGen: Controlling Sensitive Attributes for Fair Generations in Diffusion Models via Adaptive Latent Guidance", authors: "Mintong Kang, Vinayshekhar Bannihatti Kumar, Shamik Roy, et al.", href: "https://arxiv.org/pdf/2503.01872" },
  { year: "2025", venue: "NeurIPS", title: "SQLens: An End-to-End Framework for Error Detection and Correction in Text-to-SQL", authors: "Yue Gong, Chuan Lei, Xiao Qin, Kapil Vaidya, Balakrishnan Narayanaswamy, Tim Kraska", href: "https://arxiv.org/abs/2506.04494" },
  { year: "2025", venue: "VLDB", title: "Improving DBMS Scheduling Decisions with Fine-grained Performance Prediction on Concurrent Queries", authors: "Ziniu Wu, Markos Markakis, Chunwei Liu, Peter Baile Chen, et al.", href: "https://arxiv.org/abs/2501.16256" },
  { year: "2024", venue: "SoCC", title: "Vista: Machine Learning Based Database Performance Troubleshooting Framework in Amazon RDS", authors: "Vikramank Singh, Zhao Song, Balakrishnan Narayanaswamy, Kapil Vaidya, Tim Kraska", href: "https://www.amazon.science/publications/vista-machine-learning-based-database-performance-troubleshooting-framework-in-amazon-rds" },
  { year: "2024", venue: "SoCC", title: "Forecasting Algorithms for Intelligent Resource Scaling: An Experimental Analysis", authors: "Yanlei Diao, Dominik Horn, Andreas Kipf, Oleksandr Shchur, et al.", href: "https://www.amazon.science/publications/forecasting-algorithms-for-intelligent-resource-scaling-an-experimental-analysis" },
  { year: "2024", venue: "VLDB", title: "Why TPC is not enough: An analysis of the Amazon Redshift fleet", authors: "Alexander van Renen, Dominik Horn, Pascal Pfeil, Kapil Vaidya, et al.", href: "https://www.amazon.science/publications/why-tpc-is-not-enough-an-analysis-of-the-amazon-redshift-fleet" },
  { year: "2024", venue: "ICML", title: "Online Adaptive Anomaly Thresholding with Confidence Sequences", authors: "Sophia Huiwen Sun, Abishek Sankararaman, Balakrishnan Narayanaswamy", href: "https://assets.amazon.science/79/8f/8f8cbd824adf9229d6d1248f2ca1/online-adaptive-anomaly-thresholding-with-confidence-sequences.pdf" },
  { year: "2024", venue: "SIGMOD", title: "Intelligent Scaling in Amazon Redshift", authors: "Vikram Nathan, Vikramank Singh, Zhengchun Liu, et al.", href: "https://www.amazon.science/publications/intelligent-scaling-in-amazon-redshift" },
  { year: "2024", venue: "SIGMOD", title: "Stage: Query Execution Time Prediction in Amazon Redshift", authors: "Ziniu Wu, Ryan Marcus, Zhengchun Liu, et al.", href: "https://www.amazon.science/publications/stage-query-execution-time-prediction-in-amazon-redshift" },
  { year: "2024", venue: "CIDR", title: "Panda: Performance Debugging for Databases using LLM Agents", authors: "Vikramank Singh, Kapil Vaidya, Vinayshekhar Bannihatti Kumar, et al.", href: "https://www.cidrdb.org/cidr2024/papers/p6-singh.pdf" },
  { year: "2023", venue: "NeurIPS", title: "Online Robust Non-stationary Estimation", authors: "Abishek Sankararaman, Balakrishnan Narayanaswamy", href: "https://drive.google.com/file/d/1W9L9u5S10hTLuyMb0sYM5zfVH0HQVOex/view?usp=drive_link" },
  { year: "2023", venue: "SIGMOD", title: "Auto-WLM: Machine Learning Enhanced Workload Management in Amazon Redshift", authors: "Gaurav Saxena, Mohammad Rahman, Naresh Chainani, et al.", href: "https://drive.google.com/file/d/1vTbfjKxHu76lfvI80zf7hu3vWBU8R1Qk/view?usp=drive_link" },
  { year: "2020", venue: "KDD · Best Paper", title: "Temporal-Contextual Recommendation in Real-Time", authors: "Yifei Ma, Balakrishnan Narayanaswamy, Haibin Lin, Hao Ding", href: "https://www.amazon.science/publications/temporal-contextual-recommendation-in-real-time" },
];

export const additionalPatents = [
  { title: "Assisted database anomaly mitigation", inventors: "Vikramank Yogendra Singh, Zhao Song, Balakrishnan Narayanaswamy, et al.", number: "US 12,554,691", href: "https://patents.google.com/patent/US12554691B1/en" },
  { title: "Adapting concurrency to support machine learning model prediction", inventors: "Balakrishnan Narayanaswamy, Gokul Soundararajan, Jiayuan Chen, et al.", number: "US 12,547,925", href: "https://patents.google.com/patent/US12547925B1/en" },
  { title: "Predicting a future workload for scaling database processing resources for satisfying a performance objective", inventors: "Vikram Nathan, Balakrishnan Narayanaswamy, Andreas Michael Kipf, Tim Kraska", number: "US 12,530,355", href: "https://patents.google.com/patent/US12530355B1/en" },
  { title: "Query performance prediction using multiple experts", inventors: "Zhengchun Liu, Gaurav Saxena, Balakrishnan Narayanaswamy, et al.", number: "US 12,248,473", href: "https://patents.google.com/patent/US12248473B1/en" },
  { title: "Rewriting queries to compensate for stale materialized views", inventors: "Yannis Papakonstantinou, Balakrishnan Narayanaswamy, Christos Faloutsos, Vuk Ercegovac", number: "US 11,868,347", href: "https://patents.google.com/patent/US11868347B1/en" },
  { title: "Artificial intelligence system using hybrid technique for task-oriented dialog management", inventors: "Rashmi Gangadharaiah, Charles Elkan, Balakrishnan Narayanaswamy", number: "US 11,797,769", href: "https://patents.google.com/patent/US11797769B1/en" },
  { title: "Generating an ensemble of forecasting models", inventors: "Balakrishnan Narayanaswamy, Thomas George, Yogish Sabharwal, et al.", number: "US 2015/0253463 A1", href: "https://patents.google.com/patent/US20150253463A1/en" },
  { title: "Power factor", inventors: "Jagabondhu Hazra, Balakrishnan Narayanaswamy, Devasenapathi P. Seetharamakrishnan, Liyanage Chandratilak De Silva", number: "US 9,014,868", href: "https://patents.google.com/patent/US9014868B2/en" },
] as const;
